kind: DeploymentConfig
apiVersion: v1
metadata:
  name: sso
  labels:
    application: sso
    component: server
spec:
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  replicas: 1
  selector:
    deploymentConfig: sso
  template:
    metadata:
      name: sso
      labels:
        deploymentConfig: sso
        application: sso
        component: server
    spec:
      serviceAccountName: sso-service-account
      terminationGracePeriodSeconds: 30
      containers:
      - name: sso
        image: registry.access.redhat.com/redhat-sso-7/sso70-openshift:1.3-21
        imagePullPolicy: Always
        volumeMounts:
        - name: sso-demo-volume
          mountPath: "/opt/sso-demo"
          readOnly: true
        - name: eap-keystore-volume
          mountPath: "/etc/eap-secret-volume"
          readOnly: true
        - name: eap-jgroups-keystore-volume
          mountPath: "/etc/jgroups-encrypt-secret-volume"
          readOnly: true
        - name: sso-truststore-volume
          mountPath: "/etc/sso-secret-volume"
          readOnly: true
        livenessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-c"
            - "/opt/eap/bin/livenessProbe.sh"
          initialDelaySeconds: 180
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-c"
            - "/opt/eap/bin/readinessProbe.sh"
        ports:
        - name: jolokia
          containerPort: 8778
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        env:
        - name: HOSTNAME_HTTP
          value: "${SSO_HOSTNAME_HTTP}"
        - name: HOSTNAME_HTTPS
          value: "${SSO_HOSTNAME_HTTPS}"
        - name: SSO_IMPORT_FILE
          value: "${SSO_IMPORT_FILE}"
        - name: HTTPS_KEYSTORE_DIR
          value: "/etc/eap-secret-volume"
        - name: HTTPS_KEYSTORE
          value: "${HTTPS_KEYSTORE}"
        - name: HTTPS_KEYSTORE_TYPE
          value: "${HTTPS_KEYSTORE_TYPE}"
        - name: HTTPS_NAME
          value: "${HTTPS_NAME}"
        - name: HTTPS_PASSWORD
          value: "${HTTPS_PASSWORD}"
        - name: JGROUPS_ENCRYPT_SECRET
          value: "${JGROUPS_ENCRYPT_SECRET}"
        - name: JGROUPS_ENCRYPT_KEYSTORE_DIR
          value: "/etc/jgroups-encrypt-secret-volume"
        - name: JGROUPS_ENCRYPT_KEYSTORE
          value: "${JGROUPS_ENCRYPT_KEYSTORE}"
        - name: JGROUPS_ENCRYPT_NAME
          value: "${JGROUPS_ENCRYPT_NAME}"
        - name: JGROUPS_ENCRYPT_PASSWORD
          value: "${JGROUPS_ENCRYPT_PASSWORD}"
        - name: JGROUPS_CLUSTER_PASSWORD
          value: "${JGROUPS_CLUSTER_PASSWORD}"
        - name: SSO_SERVICE_USERNAME
          value: "${SSO_SERVICE_USERNAME}"
        - name: SSO_SERVICE_PASSWORD
          value: "${SSO_SERVICE_PASSWORD}"
        - name: SSO_TRUSTSTORE
          value: "${SSO_TRUSTSTORE}"
        - name: SSO_TRUSTSTORE_DIR
          value: "/etc/sso-secret-volume"
        - name: SSO_TRUSTSTORE_PASSWORD
          value: "${SSO_TRUSTSTORE_PASSWORD}"
      volumes:
      - name: sso-demo-volume
        secret:
          secretName: sso-demo-secret
      - name: eap-keystore-volume
        secret:
          secretName: "${HTTPS_SECRET}"
      - name: eap-jgroups-keystore-volume
        secret:
          secretName: "${JGROUPS_ENCRYPT_SECRET}"
      - name: sso-truststore-volume
        secret:
          secretName: "${SSO_TRUSTSTORE_SECRET}"
  triggers:
  - type: ConfigChange
